### PR TITLE
fix: use own, newly created directory

### LINKED ISSUE #129: Does not work on self-hosted runner
This action deploys necessary commands to `$HOME/bin/`(https://github.com/editorconfig-checker/action-editorconfig-checker/blob/main/src/index.ts#L14), but [the official image ](https://github.com/actions/runner/blob/main/images/Dockerfile)for self-hosted runner already has files placed in $HOME/bin/, causing unexpected behavior.

```
 % docker run -it ghcr.io/actions/actions-runner:2.319.1  /bin/sh
.
.
$ ls -l $HOME/bin
total 84736
-rwxr--r-- 1 runner docker   392736 Nov 10  2023 Azure.Core.dll
-rwxr--r-- 1 runner docker  1308080 Nov 13  2023 Azure.Storage.Blobs.dll
.
.
-rw-r--r-- 1 runner docker     5937 Aug 13 16:29 update.cmd.template
-rwxr-xr-x 1 runner docker     8748 Aug 13 16:29 update.sh.template
```

log:
```
Run editorconfig-checker/action-editorconfig-checker@v2.0.0
Find 'latest' release
Downloading 'ec-linux-arm[6](https://github.com/XXXX/XXXX/actions/runs/XXXX/job/XXXX?pr=148#step:3:7)4.tar.gz'
Extracting 'ec-linux-arm64.tar.gz'
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner -f /home/runner/_work/_temp/3c943f84-60[7](https://github.com/XXXX/XXXX/actions/runs/XXXX/job/XXXX?pr=148#step:3:8)d-4cd9-86d3-b2f97b15fc25
Rename 'Azure.Core.dll' to 'editorconfig-checker.dll'
Add to PATH
```

### PR DESCRIPTION
**Pull request by mstruebing**
I'm not entirely sure how to test this properly.

Closes #129

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -5,22 +5,33 @@ import path from 'node:path'
 import { findRelease } from './release'
 import { checkerName, version } from './shared'
 
+const WORKING_DIR = path.join(process.env.HOME ?? "/tmp", 'editorconfig-checker')
```
Comment (ccoVeille) [inline src/index.ts]: Is there any reason to do not use /tmp by default?

Couldn't we use a temporary working directory? Something equivalent to  `mktemp -d` (shell) or `os.TempDir` (Go) ?

Comment (theoludwig) [inline src/index.ts]:
```suggestion
const WORKING_DIR = path.join(os.homedir(), 'editorconfig-checker')
```

https://nodejs.org/docs/latest/api/os.html#oshomedir

Comment (theoludwig) [reply src/index.ts]: If we would like to use `/tmp`, we should use `os.tmpdir()`.

https://nodejs.org/docs/latest/api/os.html#ostmpdir

Comment (mstruebing) [reply src/index.ts]: I‘ve used that as a fallback because the environment variable could be undefined. I doubt that it ever will be, but yeah, we should guard against it.

Comment (mstruebing) [reply src/index.ts]: Thank you 🙏

**Comment by mstruebing** [comment]
cc @rskmm0chang

**Review by theoludwig — APPROVED** [review]

**Review by klaernie — APPROVED** [review]

File: src/index.ts (hunk 1 above)
Comment (ccoVeille) [reply src/index.ts]: Why using os.homedir instead of os.tmpdir?

I'm fine with the current change, because I don't understand it fully, but I'm asking to be sure

**Comment by mstruebing** [comment]
I guess 72hours are over.
